import { ASIA_IMAGE_LABELS, US_REPORT_LABELS } from './locale.ts';

const PHRASES: Array<[string, string]> = [
  ['布伦特期货行情', 'Brent futures prices'],
  ['黄金期货行情', 'Gold futures prices'],
  ['白银期货行情', 'Silver futures prices'],
  ['比特币期货行情', 'Bitcoin futures prices'],
  ['部分跨资产行情', 'some cross-asset prices'],
  ['展示已核实的行情图解、市场解读、经济数据和关键来源', 'Shows verified market charts, interpretation, economic data, and key sources'],
  ['亚洲市场收盘复盘', 'Asia market close review'],
  ['亚洲市场收盘复盘（', 'Asia market close review ('],
  ['上证指数', 'SSE Composite'],
  ['深证成指', 'SZSE Component'],
  ['创业板指', 'ChiNext Index'],
  ['指数收盘位置', 'index close position'],
  ['开盘跳空', 'opening gap'],
  ['日内振幅', 'intraday range'],
  ['涨跌分布', 'return distribution'],
  ['最高连板', 'Highest consecutive limit-up streak'],
  ['上涨家数占优', 'advancers outnumbered decliners'],
  ['站上日内均价的个股不足一半', 'fewer than half of stocks were above their intraday VWAP'],
  ['达到一半，才算上涨质量改善', 'reaches half before advance quality improves'],
  ['成交额继续收缩', 'turnover continued to contract'],
  ['指数与行业普遍收涨', 'indexes and sectors broadly gained'],
  ['尚缺：研究解释', 'Missing: research interpretation'],
  ['数据完整度与校准', 'Data completeness and calibration'],
  ['展示已核实的行情图解、市场解读、Economic data和Key sources', 'Shows verified market charts, interpretation, economic data, and key sources'],
  ['美东交易日市场图文复盘', 'U.S. trading day market review'],
  ['亚洲市场Close图文复盘', 'Asia market close review'],
  ['包含亚洲市场Close摘要、市场Breadth、Money flow、Market', 'Includes the Asia close summary, market breadth, money flow, market'],
  ['周度变化及Key sources', 'weekly changes, and key sources'],
  ['目标版 · 以报告实际生成时间和数据日期为准', 'Target edition · based on the actual report generation time and data date'],
  ['热度、脆弱度与六维分数均为Market state观察分，不直接映射仓位，也不构成交易指令。', 'Heat, fragility, and six-dimension scores are market-state observation scores; they do not map directly to position sizing or constitute trading instructions.'],
  ['越高表示该维度越强；Loss risk越高，风险越高。', 'Higher values indicate a stronger dimension; a higher loss-risk score indicates greater risk.'],
  ['收盘上涨家数占优，但站上日内均价的个股不足一半；证据:', 'Advancing stocks outnumbered decliners at the close, but fewer than half of stocks were above their intraday VWAP; evidence:'],
  ['下一观察日站上日内均价的个股达到一半，才算上涨质量改善；条件:', 'Advancing quality improves only when half of stocks are above their intraday VWAP on the next observation day; condition:'],
  ['市场从前一日的Cool脆弱转为Moderately active，指数与行业普遍收涨，但成交额继续收缩，上涨质量仍待确认。', 'The market shifted from the prior day\'s cool and fragile state to moderately active; indexes and sectors broadly gained, but turnover continued to contract and the quality of the advance remains unconfirmed.'],
  ['警告: Profit effect、Loss risk存在missing，observation score按可用指标重加权。', 'Warning: Profit effect and loss risk have missing inputs; observation scores were reweighted using available metrics.'],
  ['完整Source链接见网页报告。', 'Full source links are available in the web report.'],
  ['市场有风险，投资需谨慎。', 'Market risk applies; this is not investment advice.'],
  ['两融数据暂缺（T+1延迟）', 'Margin data unavailable (T+1 delay)'],
  ['生成方式', 'Generation method'],
  ['本报告按计划生成，生成时间为本次实际运行时间。', 'This report was generated on schedule; the generation time is the actual run time.'],
  ['数据日期', 'Data date'],
  ['报告生成时间', 'Report generation time'],
  ['周二 盘后点评', 'Tuesday after-market review'],
  ['最高连板', 'Highest consecutive limit-up streak'],
  ['涨停代表', 'Representative limit-up stocks'],
  ['跌幅靠前行业', 'Worst-performing sectors'],
  ['高成交核心票 TOP10', 'Top 10 high-volume core stocks'],
  ['涨幅前五', 'Top five gainers'],
  ['跌幅前五', 'Top five decliners'],
  ['完整度: 高', 'Completeness: high'],
  ['六维可用', 'Six dimensions available'],
  ['校准: 暂定观察刻度（未回测）。', 'Calibration: provisional observation scale (not backtested).'],
  ['市场状态温和活跃', 'Market state: moderately active'],
  ['市场状态偏冷且脆弱', 'Market state: cool and fragile'],
  ['市场状态偏冷', 'Market state: cool'],
  ['市场信息仅供研究参考。', 'For research reference only.'],
  ['市场信息仅供研究参考', 'For research reference only'],
  ['尚无通过逐点审核的公开图表数据', 'No point-reviewed public chart data is available'],
  ['缺少的数据会标为缺项。完整数值、方法和来源见网页报告。', 'Missing data is labelled explicitly. Full values, methods, and sources are available in the web report.'],
  ['完整数值、方法和来源见网页报告。', 'Full values, methods, and sources are available in the web report.'],
  ['收盘复盘', 'Market close review'],
  ['亚洲市场收盘复盘', 'Asia market close review'],
  ['美股收盘复盘', 'U.S. market close review'],
  ['图解、解读与来源', 'Charts, interpretation, and sources'],
  ['美东交易日', 'U.S. trading day'],
  ['北京时间', 'Beijing time'],
  ['目标日期', 'Target date'],
  ['原报告生成于', 'Source report generated at'],
  ['报告日期', 'Report date'],
  ['市场状态', 'Market state'],
  ['状态', 'Status'],
  ['温和活跃', 'Moderately active'],
  ['偏冷且脆弱', 'Cool and fragile'],
  ['偏冷', 'Cool'],
  ['热度 / 脆弱度', 'Heat / fragility'],
  ['观察分', 'observation score'],
  ['口径', 'Methodology'],
  ['六维观察', 'Six-dimension observation'],
  ['观察分越高表示该维度越强；亏钱风险越高，风险越高。', 'A higher score indicates a stronger dimension; a higher loss-risk score indicates greater risk.'],
  ['流动性', 'Liquidity'],
  ['广度', 'Breadth'],
  ['赚钱效应', 'Profit effect'],
  ['亏钱风险', 'Loss risk'],
  ['趋势确认', 'Trend confirmation'],
  ['轮动质量', 'Rotation quality'],
  ['核心矛盾', 'Core tension'],
  ['次日观察', 'Next-session watch'],
  ['明日验证', 'Next-day validation'],
  ['指数总览', 'Index overview'],
  ['市场总览', 'Market overview'],
  ['涨跌停', 'Price limits'],
  ['资金动向', 'Money flow'],
  ['融资融券', 'Margin financing'],
  ['行业板块', 'Industry sectors'],
  ['高成交个股', 'High-volume stocks'],
  ['热门概念', 'Hot concepts'],
  ['极端异动', 'Extreme movers'],
  ['数据完整度与校准', 'Data completeness and calibration'],
  ['数据状态', 'Data status'],
  ['当日公开复盘。', 'Public same-day review.'],
  ['尚缺：研究解释', 'Missing: research interpretation'],
  ['关键来源', 'Key sources'],
  ['亚洲市场图表', 'Asian market charts'],
  ['综合盘面', 'Market breadth dashboard'],
  ['资金流向', 'Money flow'],
  ['热点概念', 'Hot concepts'],
  ['市场温度', 'Market temperature'],
  ['周度概览', 'Weekly overview'],
  ['四大指数收盘涨跌', 'Four major index returns'],
  ['美股个股日涨跌', 'U.S. stock daily returns'],
  ['美债收益率水平', 'U.S. Treasury yield levels'],
  ['美债收益率当日变动', 'U.S. Treasury daily yield changes'],
  ['跨资产日涨跌', 'Cross-asset daily returns'],
  ['经济数据', 'Economic data'],
  ['标普 500', 'S&P 500'],
  ['道指', 'Dow Jones'],
  ['纳指', 'Nasdaq'],
  ['罗素 2000', 'Russell 2000'],
  ['2 年期美债收益率水平', '2-year Treasury yield'],
  ['5 年期美债收益率水平', '5-year Treasury yield'],
  ['10 年期美债收益率水平', '10-year Treasury yield'],
  ['30 年期美债收益率水平', '30-year Treasury yield'],
  ['2 年期美债', '2-year Treasury'], ['5 年期美债', '5-year Treasury'],
  ['10 年期美债', '10-year Treasury'], ['30 年期美债', '30-year Treasury'],
  ['比特币期货', 'Bitcoin futures'],
  ['布伦特', 'Brent'],
  ['黄金', 'Gold'],
  ['白银', 'Silver'],
  ['BTC/USD 现货', 'BTC/USD spot'],
  ['观测日', 'Observed'],
  ['收盘', 'Close'],
  ['美元/桶', 'USD/barrel'],
  ['美元/金衡盎司', 'USD/troy oz'],
  ['美元/BTC', 'USD/BTC'],
  ['美元', 'USD'],
  ['美国财政部', 'U.S. Treasury'],
  ['数据: Tushare / market-data-platform', 'Data: Tushare / market-data-platform'],
  ['主题: 研究编辑部', 'Desk: Research editorial'],
  ['生成:', 'Generated:'],
  ['同比', 'YoY'],
  ['失业率', 'Unemployment rate'],
  ['非农就业月变动', 'Nonfarm payroll change'],
  ['千人', ' thousand'],
  ['尚缺：', 'Missing: '],
  ['金银或比特币行情', 'gold, silver, or Bitcoin prices'],
  ['完整Source链接', 'Full source links'],
  ['数据暂缺', 'Data unavailable'],
  ['缺项', 'missing'],
  ['上涨', 'Up'],
  ['下跌', 'Down'],
  ['平盘', 'Flat'],
  ['上涨率', 'up rate'],
  ['跌幅', 'decline'],
  ['涨幅', 'return'],
  ['涨停率', 'limit-up rate'],
  ['跌停率', 'limit-down rate'],
  ['成交额', 'turnover'],
  ['成交', 'volume'],
  ['万亿', 'trillion'],
  ['亿', ' hundred million'],
  ['板', ' boards'],
  ['站上VWAP占比', 'above-VWAP share'],
  ['站上日内均价', 'above intraday VWAP'],
  ['个股', 'stocks'],
  ['指数', 'indexes'],
  ['行业', 'sectors'],
  ['概念', 'concept'],
  ['龙头', 'leader'],
  ['代码', 'Ticker'],
  ['中位数', 'median'],
  ['均涨跌', 'average return'],
  ['总成交', 'total turnover'],
  ['家', ' stocks'],
  ['行业 / 均涨跌 / 中位数 / 家数 / 上涨率', 'Industry / average return / median / count / up rate'],
  ['概念 / 涨幅 / 龙头 / 涨停数', 'Concept / return / leader / limit-up count'],
  ['来源', 'Source'],
];


const COMPLETE_TERMS: Array<[string, string]> = [
  ['市场状态从温和活跃转为中性偏冷，指数层面分化，个股广度明显走弱', 'The market shifted from moderately active to neutral-to-cool; indexes diverged and stock breadth weakened markedly'],
  ['市场状态中性偏冷', 'Market state: neutral to cool'],
  ['市场广度', 'Market breadth'], ['综合仪表盘', 'Market breadth dashboard'],
  ['资金流向图', 'Money flow'], ['热点概念图', 'Hot concepts'], ['市场温度计', 'Market temperature'],
  ['涨跌停榜单', 'price-limit list'], ['至', 'to'],
  ['下一观察日上涨家数占比高于当前值，才算广度开始修复', 'Breadth starts to recover only if the advancing stock share exceeds its current level on the next observation day'],
  ['生成时间', 'Generation time'], ['报告生成方式', 'Report generation method'],
  ['周三 盘后点评', 'Wednesday after-market review'], ['维度', 'Dimension'],
  ['昨日验证复盘', 'Prior-day validation review'], ['科创50', 'STAR Market 50'],
  ['沪深300', 'CSI 300'], ['中证500', 'CSI 500'], ['中证1000', 'CSI 1000'],
  ['站上 VWAP 比例', 'Above-VWAP share'], ['日内振幅中位数', 'Median intraday range'], ['收盘位置', 'Close position'],
  ['美容护理', 'Beauty and personal care'], ['农林牧渔', 'Agriculture, forestry and fisheries'],
  ['公用事业', 'Utilities'], ['其他', 'Other'], ['煤炭', 'Coal'], ['交通运输', 'Transportation'],
  ['机械设备', 'Machinery'], ['纺织服饰', 'Textiles and apparel'],
  ['一、', 'I. '], ['二、', 'II. '], ['三、', 'III. '], ['四、', 'IV. '], ['五、', 'V. '],
  ['六、', 'VI. '], ['七、', 'VII. '], ['八、', 'VIII. '], ['九、', 'IX. '], ['十、', 'X. '],
  ['行业层面多数上涨，但个股广度没有同步确认', 'Most sectors advanced, but stock breadth did not confirm the move'],
  ['下一观察日上涨个股家数占比高于当前值，才算广度开始修复', 'Breadth starts to recover only if the advancing stock share exceeds its current level on the next observation day'],
  ['融资余额最新观测日早于上一交易日，保留原始观测日', 'The latest financing-balance observation predates the previous session; original observation dates are preserved'],
  ['融资余额非最新交易日；保留实际观测日。', 'Financing balances are not from the latest session; actual observation dates are preserved.'],
  ['本期仅含', 'This edition includes only '],
  ['个可用交易日', ' available sessions'],
  ['逐点保留实际观测日，不补造缺失交易日', 'Actual observation dates are retained for each point; missing sessions are not fabricated'],
  ['保留实际观测日，不补造缺失交易日', 'Actual observation dates are retained; missing sessions are not fabricated'],
  ['上涨率', 'Advancing share'], ['个股中位涨跌', 'Median stock return'],
  ['成交额加权涨跌', 'Turnover-weighted return'], ['成交额加权与中位数偏离', 'Turnover-weighted return minus median'],
  ['高成交标的相对偏强', 'High-turnover stocks were relatively stronger'],
  ['成交额分位', 'Turnover percentile'], ['成交额/历史中位', 'Turnover / historical median'],
  ['历史中位', 'historical median'], ['站上VWAP占比', 'Above-VWAP share'],
  ['涨幅超5%占比', 'Share gaining over 5%'], ['跌幅超5%占比', 'Share falling over 5%'],
  ['上涨指数占比', 'Advancing index share'], ['指数中位涨跌', 'Median index return'],
  ['上涨行业占比', 'Advancing sector share'], ['行业中位涨跌', 'Median sector return'],
  ['领涨集中度', 'Leader concentration'], ['中性偏冷', 'Neutral to cool'],
  ['偏弱', 'Somewhat weak'], ['较弱', 'Weak'], ['较强', 'Strong'], ['偏强', 'Somewhat strong'],
  ['中性', 'Neutral'], ['低风险', 'Low risk'], ['已核实', 'Verified'],
  ['部分缺项', 'Degraded'], ['逐点审核未通过，本期不公开该图数据', 'Point review did not pass; this chart is withheld for this edition'],
  ['主力净流入', 'Major net inflows'], ['主力净流出', 'Major net outflows'],
  ['净流入', 'Net inflows'], ['净流出', 'Net outflows'],
  ['平均涨跌', 'Average return'], ['涨停家数', 'Limit-up stocks'],
  ['上涨家数', 'Advancing stocks'], ['下跌家数', 'Declining stocks'], ['平盘家数', 'Unchanged stocks'],
  ['融资余额走势', 'Financing-balance trend'], ['融资余额', 'Financing balance'],
  ['近几日涨跌分布', 'Recent return distribution'], ['成交额走势（亿）', 'Turnover trend (CNY 100m)'],
  ['近5个可用交易日概览', 'Recent available-session overview'],
  ['近5个工作日可用数据概览', 'Available data in the last five weekdays'],
  ['已核实数据', 'Verified data'], ['热点权重', 'Hot-concept values'],
  ['Tushare A 股日线', 'Tushare A-share daily prices'],
  ['Tushare 涨跌停榜单', 'Tushare price-limit list'],
  ['Tushare 连板天梯', 'Tushare consecutive limit-up rankings'],
  ['Tushare 融资融券交易汇总', 'Tushare margin-financing summary'],
  ['Tushare 同花顺资金流', 'Tushare THS money flow'],
  ['Tushare A股晚报六维观察', 'Tushare A-share evening six-dimension observation'],
  ['东方财富概念板块（Tushare 授权数据）', 'Eastmoney concept sectors (data authorized through Tushare)'],
  ['mRNA概念', 'mRNA theme'], ['重组蛋白', 'Recombinant proteins'], ['玉米', 'Corn'], ['转基因', 'Genetically modified crops'],
  ['医药生物', 'Pharmaceuticals and biotechnology'], ['食品饮料', 'Food and beverages'], ['银行', 'Banking'],
  ['房地产', 'Real estate'], ['传媒', 'Media'], ['计算机', 'Computers'],
  ['电力设备', 'Power equipment'], ['通信', 'Telecom'], ['有色金属', 'Nonferrous metals'],
  ['环保', 'Environmental services'], ['电子', 'Electronics'], ['钢铁', 'Steel'], ['石油石化', 'Oil and petrochemicals'],
  ['行业', 'Industry'], ['家数', 'Stock count'], ['证据', 'Evidence'], ['条件', 'Condition'],
  ['全市场中位数涨跌', 'Median market return'], ['涨停数', 'Limit-up count'],
  ['总成交', 'Total turnover'], ['涨停', 'Limit-up'], ['跌停', 'Limit-down'],
  ['大单资金代理', 'Large-order money-flow proxy'], ['成交额', 'Turnover'],
  ['亿美元', ' USD 100m'], ['万亿美元', ' USD trillion'],
  ['亿元', ' CNY 100m'], ['万亿元', ' CNY trillion'],
  ['亿至', ' 100m to '], ['亿到', ' 100m to '],
  ['亿', ' 100m'], ['万亿', ' trillion'], ['家', ' stocks'],
  ['观察分（风险）', 'observation score (risk)'],
  ['板', ' consecutive limit-up sessions'], ['涨', 'advancing'], ['跌', 'declining'], ['平', 'unchanged'],
  ['均涨跌', 'Average return'], ['涨跌', 'Return'], ['涨幅', 'Return'], ['跌幅', 'Decline'],
  ['热度、脆弱度与六维分数均为市场状态观察分，不直接映射仓位，也不构成交易指令', 'Heat, fragility, and six-dimension scores are market-state observation scores; they do not map directly to position sizing or constitute trading instructions'],
  ['观察分越高表示该维度越强；亏钱风险越高，风险越高', 'Higher scores indicate stronger dimensions; a higher loss-risk score indicates greater risk'],
  ['赚钱效应、亏钱风险存在缺项，观察分按可用指标重加权', 'Profit effect and loss risk have missing inputs; observation scores were reweighted using available metrics'],
  ['校准: 暂定观察刻度（未回测）。', 'Calibration: provisional observation scale (not backtested).'],
  ['行业 / 均涨跌 / 中位数 / 家数 / 上涨率', 'Industry / average return / median / stock count / advancing share'],
  ['完整来源链接见网页报告', 'Full source links are available in the web report'],
  ['警告', 'Warning'], ['暂定观察刻度', 'provisional observation scale'], ['未回测', 'not backtested'],
  ['亚洲市场收盘图文复盘', 'Asia market close review'],
  ['包含亚洲市场收盘摘要、市场广度、资金流向、市场温度、周度变化及关键来源', 'Includes the Asia close summary, market breadth, money flow, market temperature, weekly changes, and key sources'],
];

const dictionary = new Map<string, string>([...PHRASES, ...COMPLETE_TERMS, ...Object.values(ASIA_IMAGE_LABELS), ...Object.values(US_REPORT_LABELS)]);
const terms = [...dictionary.keys()].sort((left, right) => right.length - left.length);
const letter = /\p{L}/u;

function translatePlain(value: string): string {
  let result = '';
  let offset = 0;
  while (offset < value.length) {
    const source = terms.find((term) => value.startsWith(term, offset)
      && (!letter.test(term[0]) || offset === 0 || !letter.test(value[offset - 1]))
      && (!letter.test(term.at(-1) || '') || !letter.test(value[offset + term.length] || '')));
    if (source) {
      result += dictionary.get(source);
      offset += source.length;
    } else {
      // Preserve unknown contiguous Chinese names/prose intact, never translate a
      // familiar character inside a company name or an unreviewed sentence.
      const original = value.slice(offset).match(/^[\p{L}_]+/u)?.[0] || value[offset];
      result += original;
      offset += original.length;
    }
  }
  return result.replace(/；/g, '; ').replace(/：/g, ': ').replace(/。/g, '. ')
    .replace(/，/g, ', ').replace(/、/g, ', ').replace(/（/g, ' (').replace(/）/g, ')');
}

/** Translate presentation text only; preserve facts, source names, links and SVG attributes. */
export function toEnglishPresentation(value: string): string {
  if (/^\s*<svg\b/.test(value)) {
    return value.replace(/<(?:[^"'>]|"[^"]*"|'[^']*')*>|[^<]+/g, (part) => part.startsWith('<') ? part : toEnglishPresentation(part));
  }
  return value.split(/(https?:\/\/[^\s<>"']+|\]\([^\n)]+\))/g)
    .map((part) => /^(?:https?:\/\/|\]\()/.test(part) ? part : translatePlain(part)).join('');
}
